-- Create the account_type enum
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

-- Create the classification table
CREATE TABLE IF NOT EXISTS public.classification
(
    classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    classification_name character varying NOT NULL,
    CONSTRAINT classification_pkey PRIMARY KEY (classification_id)
);

-- Create the inventory table
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year integer NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9,0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create the relationship between classification and inventory
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id)
    MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Create the account table
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Insert classification data
INSERT INTO classification (classification_name)
VALUES ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan');

-- Insert inventory data
INSERT INTO inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES 
('Jeep', 'Wrangler', 2019, 'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as off-roading whether that be on the rocks or in the mud!', '/images/jeep-wrangler.jpg', '/images/jeep-wrangler-tn.jpg', 28045, 4157, 'Orange', 1),
('Ford', 'Model T', 1921, 'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.', '/images/ford-modelt.jpg', '/images/ford-modelt-tn.jpg', 30000, 2100, 'Black', 2),
('Lamborghini', 'Adventador', 2016, 'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws.', '/images/lambo-Adve.jpg', '/images/lambo-Adve-tn.jpg', 417650, 1278, 'Blue', 2),
('Aerocar International', 'Aerocar', 1963, 'Are you sick of rush hour traffic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get this one while it lasts!', '/images/aerocar.jpg', '/images/aerocar-tn.jpg', 700000, 16458, 'Red', 1),
('Monster', 'Truck', 1995, 'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you the traction needed to jump and roll in the mud.', '/images/monster.jpg', '/images/monster-tn.jpg', 150000, 3998, 'purple', 1),
('Cadillac', 'Escalade', 2019, 'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.', '/images/escalade.jpg', '/images/escalade-tn.jpg', 75195, 41958, 'Black', 3),
('GM', 'Hummer', 2016, 'Do you have 6 kids and like to go off-roading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 56564, 'Yellow', 3),
('Mechanic', 'Special', 2000, 'Not sure where this car came from. However with a little tender loving care it will run as good as new.', '/images/ms.jpg', '/images/ms-tn.jpg', 3500, 285133, 'Rust', 5),
('Ford', 'Crown Victoria', 2003, 'After the police force updated their fleet these cars are now available to the public! These cars come equipped with the siren which is convenient for college students running late to class.', '/images/crown-vic.jpg', '/images/crown-vic-tn.jpg', 10000, 108247, 'White', 5),
('Chevy', 'Camaro', 2018, 'If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101, 'Silver', 5),
('Cadillac', 'Escalade', 2019, 'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.', '/images/escalade.jpg', '/images/escalade-tn.jpg', 75195, 41958, 'Black', 3),
('Nissan', 'Altima', 2020, 'The Nissan Altima is a reliable, fuel-efficient sedan that offers a comfortable ride and modern features at an affordable price.', '/images/altima.jpg', '/images/altima-tn.jpg', 23000, 12500, 'Blue', 5);

-- Copy of query 4 from Task 1: Modify the "GM Hummer" description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Copy of query 6 from Task 1: Update file paths to add "/vehicles" in the middle
UPDATE inventory
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');